alter table jbpm.ESCIDOC_WORKFLOWDEFINITIONS drop FOREIGN KEY FK_WORKFLOWTYPE;

alter table jbpm.ESCIDOC_STARTACTORS drop FOREIGN KEY FK_WORKFLOWDEFINITION;

alter table jbpm.ESCIDOC_WORKFLOWDEFINITIONS CHANGE WORKFLOWDEFINITION_ID WORKFLOWDEFINITION_ID varchar(255);
alter table jbpm.ESCIDOC_WORKFLOWTYPES CHANGE WORKFLOWTYPE_ID WORKFLOWTYPE_ID varchar(255);
alter table jbpm.ESCIDOC_STARTACTORS CHANGE STARTACTOR_ID STARTACTOR_ID varchar(255);

alter table jbpm.ESCIDOC_WORKFLOWDEFINITIONS CHANGE WORKFLOWTYPE_ID WORKFLOWTYPE_ID varchar(255);
alter table jbpm.ESCIDOC_STARTACTORS CHANGE WORKFLOWDEFINITION_ID WORKFLOWDEFINITION_ID varchar(255);

alter table jbpm.ESCIDOC_WORKFLOWDEFINITIONS 
    add constraint FK_WORKFLOWTYPE 
    foreign key (WORKFLOWTYPE_ID) 
    references jbpm.ESCIDOC_WORKFLOWTYPES;
    
alter table jbpm.ESCIDOC_STARTACTORS 
    add constraint FK_WORKFLOWDEFINITION 
    foreign key (WORKFLOWDEFINITION_ID) 
    references jbpm.ESCIDOC_WORKFLOWDEFINITIONS;

DROP TABLE jbpm.ESCIDOC_WM_IDS CASCADE;
